set nocompatible
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let eq = ''
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      let cmd = '""' . $VIMRUNTIME . '\diff"'
      let eq = '"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3 . eq
endfunction

"打开语法高亮
syntax on

set helplang=cn

set autoread

"设置背景
colorscheme desert
set background=dark

"设置命令行高度
set cmdheight=2

"显示行号
set nu

"设置标尺
set ruler

set laststatus=2

"for tab {
"根据文件中其他地方的缩进空格个数来确定一个tab是多少个空格
set smarttab

"tab宽度
set tabstop=4

"每一级缩进是4个空格
set shiftwidth=4

"将tab替换成空格
set expandtab
"}

"for search {
"检索时忽略大小写
set ignorecase

"查找结果高亮显示
set hlsearch
"}

"for backup {
set nobackup
set nowb
set noswapfile
"}

"使用utf-8或gbk打开文件
set fileencodings=uft-8,gbk

"设置编码
set encoding=utf-8

set ffs=unix,dos,mac

"最大化窗口
au GUIEnter * simalt ~x
